[package]
name = "clippy-6902-repro"
version = "0.1.0"
authors = ["Yoshitomo Nakanishi <yurayura.rounin.3@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
macros = {path = "macros"}
