[package]
name = "macros"
version = "0.1.0"
authors = ["Yoshitomo Nakanishi <yurayura.rounin.3@gmail.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
syn = { version = "1.0", features = ["full"] }
proc-macro2 = "1.0"
quote = "1.0"
